### ISSUE TITLE
ClusteredEventbusTest publish randomly fails

### ISSUE THREAD

**Issue by zyclonite** [vert-x3/vertx-ignite#105]
### Version

4.0.0

### Context

Every 10 to 20 runs one of the publish tests fails.

### Steps to reproduce

Overriding one of the IgniteClusteredEventbusTests e.g.
```
  @Test
  @Repeat(times = 100)
  public void testPublishJsonArray() {
    super.testPublishJsonArray();
  }
```
After some cycles the test will run into the 2min timeout

### Extra

* It looks like a vertx-core test base issue as the publishing of the message is done too early (and once too often)

**Comment by vietj** [comment]
can you fix that soon @zyclonite ?

**Comment by jo5ef** [comment]
@vietj it's fixed [here](https://github.com/eclipse-vertx/vert.x/pull/3781)

**Comment by zyclonite** [comment]
from ignite it's fine, just needs the fix from Josef in vertx-core to resolve
