### ISSUE TITLE
NodeListener from HAManagerImpl maybe not invoked (race condition)

### ISSUE THREAD

**Issue by DemonicTutor** [vert-x3/vertx-ignite#117]
### Version

4.1.1

Some versions earlier (at the time the first race-condition fix was commited) it was thread safe because of invocation ordering.

### Context

I noticed that the NodeListener from HAManager somethimes does not get invoked and i think its a race between HAManager#init and IgniteClusterManager#join / #leave.

IgniteClusterManager sets a listener in Ignite which is executed on a Ignite-Thread that then schedules back to `vertx.executeBlocking`.

Now when this Listener triggers and then the worker thread executes [this block](https://github.com/vert-x3/vertx-ignite/blob/4.1.1/src/main/java/io/vertx/spi/cluster/ignite/IgniteClusterManager.java#L297-L332) the NodeListener may not be visible.

Vertx initialization clustered:
[VertxImpl # clusterManager.join()](https://github.com/eclipse-vertx/vert.x/blob/4.1.1/src/main/java/io/vertx/core/impl/VertxImpl.java#L215)
[IgniteClusterManager # join()](https://github.com/vert-x3/vertx-ignite/blob/4.1.1/src/main/java/io/vertx/spi/cluster/ignite/IgniteClusterManager.java#L301)

[VertxImpl # initializeHaManager](https://github.com/eclipse-vertx/vert.x/blob/4.1.1/src/main/java/io/vertx/core/impl/VertxImpl.java#L245-L253)
[HAManager # init()](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/impl/HAManager.java#L143) 
[IgniteClusterManager # nodeListener()](https://github.com/vert-x3/vertx-ignite/blob/4.1.1/src/main/java/io/vertx/spi/cluster/ignite/IgniteClusterManager.java#L190)

### Do you have a reproducer?

no - i think its pretty obvious.

### Steps to reproduce

1. Start first clustered vertx instance.
2. logging breakpoint in HAManagerImpl NodeListener
3. Start / stop more clustered vertx instances joining / leaving first
4. NodeListener may or may not be set

### Extra

OpenJDK 16

**Comment by zyclonite** [comment]
@DemonicTutor if you want this fix for version 4.1.2, please create a separate PR for the 4.1 branch
