### ISSUE TITLE
GridName

### ISSUE THREAD

**Issue by alexGalushka** [vert-x3/vertx-ignite#12]
@agura  I've realized that whenever we .start() the new grid we generate the unique ID for the node and set it in the Ignite config, we use the same exact ID and vertx prefix to set the gridName in the Ignite config. Whenever we instantiate the IgniteClusterManager it would be nice to get the node Id generated, so the setNodeId could be called from the constructor instead of loadConfiguration() and the parameter nodeId could be set... Also, the gridName value if set in the xml config file is being overwritten as per today implementation...

P.S
Maybe I'm overthinking it or just didn't get the basics of Apache Ignite, can you please bring some light on "What are the definitions of the grid, node, cluster in the context of Apache Ignite?"

**Comment by alexGalushka** [comment]
@agura I took a stab on it in this [PR](https://github.com/vert-x3/vertx-ignite/pull/13), plz take a look

**Comment by agura** [comment]
@alexGalushka I took a look at your PR and I think that it should simpler. I think that it is enough no initialize `nodeID` filed during object instantiation and then use it in `setNodeId` method. 

```java
private String nodeID = UUID.randomUUID().toString();
```
By the way, `setNodeId` method should be renamed to `setNodeID` because we already have `getNodeID` method.

Also see my comments to PR itslef.

I'll create new PR today.

**Comment by agura** [comment]
See PR #14.

**Comment by alexGalushka** [comment]
@agura I think I'm confused by inconsistent Apache Ignite documentation, I'm trying to square this away at the[ Ignite forum](http://apache-ignite-users.70518.x6.nabble.com/Ignite-terminology-td3687.html#a3709). It seems like from Vladimir's response that the gridName is actually gridInstanceName, and as you said the "node name". How to name the cluster (I naively assumed that gridName is the clusterName)? Or there is now such a thing in Ignite? I know that there is a dynamic node grouping naming within the cluster...

**Comment by agura** [comment]
For now `gridName` is just node name. It is impossible to start multiple nodes with the same `gridName`.

**Comment by alexGalushka** [comment]
@agura I run the each Ignite node in the docker container, so I have dedicated JVM and Vert.x instance per node... In this case the same gridName (cluster name, not the node name) will work, but the problem is that there is no true gridName, it's just a node name :-(

**Comment by agura** [comment]
Why do you need grid name?

**Comment by alexGalushka** [comment]
I need the cluster (grid) name to get all the nodes which belong to this cluster and then target the particular node, or all of them in this cluster. I initially thought that with Ignition.ignite("MY_CLUSTER_NAME").cluster().nodes() I can achieve that...

**Comment by agura** [comment]
Cluster defines as set of nodes that connect each other. So `Ignition.localIgnite().cluster().nodes()` will return you all cluster nodes.

**Comment by alexGalushka** [comment]
Andrey, thanx a ton, I think I'm eventually getting the Ignite concept
here: so if ignite nodes discover each other (discovery configuration
defines the cluster), then each node in that defined cluster aware about
all the nodes of the cluster and Ignition.localIgnite().cluster().nodes() will
return all the nodes of that cluster.

**Comment by agura** [comment]
@alexGalushka Do you still need this issue to be implemented?

**Comment by alexGalushka** [comment]
@agura I'm not blocked, thank you for clarifying a few things here :) But it would be nice to give the node custom node through the configuration file, someone eventually will need it and will be wondering why the config setting for gridName is not working. However since we've exposed the node ID on the IgniteClusterManger instantiation, we can derive gridName (node name) from the vertx prefix and node ID...  What's your opinion on this?

**Comment by agura** [comment]
@alexGalushka Actually, I don't understand how node ID or grid name can be useful in case of using Ignite as vert.x cluster manager.

**Comment by agura** [comment]
Fixed by #14.

**Comment by alexGalushka** [comment]
@agura I've played around with multiple ways on how to get the collection of nodes which belong to one specific cluster. 

My setup: VM {Ubuntu 15.04; 4 cores}, 2 docker containers (each has its own JVM, each deploys its own Vert.x clustered with Apache Ignite as a cluster manager, I use multicast for node discovery)

First, Ignition.localIgnite().cluster().nodes() returns NULL

Also in the javadoc to localignite it says: "According to contract this method has to be called only under IgniteThread. An IllegalArgumentException will be thrown otherwise." 

Second, Ignition.ignite(UUID.fromString(nodeID)).cluster().nodes() - same result

But, interesting finding from the javadoc: "Note that **grid instance** and **local node** have one-to-one relationship where node has ID and** instance has name of the grid to which both grid instance and its node belong**." 

So per this javadoc there is a grid (cluster) name, it's not a node name, it's a name of the cluster which node belongs to!

Third, 
I've added this: <property name="gridName" value="APPLIANCE"/> to ignite xml config file.

To get all the nodes which belong (assuming that the javadoc is correct) to the grid with name "APPLIANCE":

    System.out.println("Here are the nodes in the APPLIANCE : "
        + Ignition.localIgnite().cluster().nodes()
        .stream().map(node -> node.id()).collect(Collectors.toList()).toString());

It returns the expected result!

This is the reason I'd like user of vertx-ignite to be able to set the gridName property in the config file and not being overwritten.

**Comment by agura** [comment]
@alexGalushka I think that using `gridName` for getting all cluster nodes isn't good idea. `gridName` is usefull for testing purposes but from my point of view it brings some difficulties during configuration and support.

I haveworkaround for you that allows get all cluster nodes:

```java
        List<Ignite> grid = Ignition.allGrids();

        Ignite localIgnite = F.first(grid);

        Collection<ClusterNode> nodes = localIgnite.cluster().nodes();
```

If you run your nodes in different JVMs then `Ignition.allGrids()` always returns exactly one element in list and it is exactly same `Ignite` instance as your local Ignite instance. So you can use it for getting cluster nodes.

**Comment by alexGalushka** [comment]
@agura I've tested it. The IDs which I get on IgniteClusterManager instantiation don't match the IDs I get from the nodes using the suggested workaround.

Here is the print puts from console (for one node):

cpcontainer2_1 | ****** Main Method has been invoked ******
cpcontainer2_1 | ****** IN MAIN the NODE ID is: **7df060f3-493c-4498-9687-65de833716b5**
cpcontainer2_1 | ***** Starting the IgniteVerticle
cpcontainer2_1 | ***** NODE ID passed in on verticle launch is: **7df060f3-493c-4498-9687-65de833716b5**
cpcontainer2_1 | ****** Starting IgniteVerticle on the node with IP: 172.17.0.2 on the appliance #1 ******
cpcontainer2_1 | ****** GridName is: null
cpcontainer2_1 | ****** GridName (same but different way) is: null
cpcontainer2_1 | Here are the nodes in the APPLIANCE : [TcpDiscoveryNode [id=**92111514-2aeb-4cc8-b10b-af254445e6df**, addrs=[0:0:0:0:0:0:0:1%lo, 127.0.0.1, 172.17.0.3], sockAddrs=[/0:0:0:0:0:0:0:1%lo:47500, /0:0:0:0:0:0:0:1%lo:47500, /127.0.0.1:47500, /172.17.0.3:47500], discPort=47500, order=1, intOrder=1, lastExchangeTime=1459521263495, loc=false, ver=1.5.0#20151229-sha1:f1f8cda2, isClient=false], TcpDiscoveryNode [id=**b01b3847-6726-438a-aba8-83384e6f5aa4**, addrs=[0:0:0:0:0:0:0:1%lo, 127.0.0.1, 172.17.0.2], sockAddrs=[02d4fee787f1/172.17.0.2:47500, /0:0:0:0:0:0:0:1%lo:47500, /127.0.0.1:47500, /172.17.0.2:47500], discPort=47500, order=2, intOrder=2, lastExchangeTime=1459521264697, loc=true, ver=1.5.0#20151229-sha1:f1f8cda2, isClient=false]]
cpcontainer2_1 | ****** I am : GOOD

**Comment by alexGalushka** [comment]
@agura I got the ID match when I use the gridName 

System.out.println("Here are the nodes in the APPLIANCE : "
        + Ignition.ignite("APPLIANCE").cluster().nodes()
        .stream().map(node -> node.id()).collect(Collectors.toList()).toString());

**Comment by agura** [comment]
@alexGalushka From log I see only node IDs but don't see expected node IDs. Could you please provide you test code snippet?

**Comment by alexGalushka** [comment]
@agura my bad, the workaround works! for some weird reason I've been using my forked vertx-ignite with the initial PR changes, which had the setConsistentId() instead of setNodeId, that has caused the ID mismatch. Thank you, Andrey!
