### ISSUE TITLE
Have you considered adding support for GridGain?

### ISSUE THREAD

**Issue by zhouzhou19950825** [vert-x3/vertx-ignite#130]
#### Read me

At present, ignite's support for jdk17 is not very good, but gridgain's support is good.
Have you considered adding support for GridGain?

**Comment by zhouzhou19950825** [comment]
@zyclonite On jdk17,  need to add the corresponding vmoptions to start

--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
--add-opens=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED
--add-opens=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
--add-opens=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED
--add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED
--add-opens=java.base/java.math=ALL-UNNAMED
--add-opens=java.sql/java.sql=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED

**Comment by zhouzhou19950825** [comment]
@zyclonite  For the completeness of the document, the vm parameter content is added
https://github.com/vert-x3/vertx-ignite/pull/131

**Comment by tsegismont** [comment]
Thank you @zhouzhou19950825 for #131 

@zyclonite I believe we can close this one now, can't we?
