### ISSUE TITLE
Lock is not released when node goes down

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-ignite#23]
Following up on eclipse/vert.x#1609, I have tried to apply the new lock tests, which verify that a lock is released when the holding node is killed or goes down.

It seems the current implementation does not support this. Maybe it could be reworked around cache locks?

**Comment by agura** [comment]
@tsegismont I don't think that lock should be released in case of node gone. Actually lock is held by cluster but node particular node.

**Comment by tsegismont** [comment]
That is not true. If a lock acquired on a node isn't released when this
node goes down, then no other node will be able to acquire it later.

2016-09-26 20:46 GMT+02:00 Andrey Gura <notifications@github.com>:
