### ISSUE TITLE
Ghost message consumer

### ISSUE THREAD

**Issue by onesse** [vert-x3/vertx-ignite#44]
Hello,

I need to place the context :
- 2 machines (VMs) described as A and B below,
- vertx 3.4.1 + ignite
- ssl off
- A and B are connected with a distributed event-bus and A sending messages to B then B send them back to A.

Stops node A and restart it ... messages received by A are consumed twice (or sent twice by B) ! Restart one more time A, messages are consumed three times by A. 

I wrote a simple reproducer here : https://github.com/onesse/vertx-ghost-consumer 

Hope this will help you to understand my problem. 

Regards,

JP

**Comment by agura** [comment]
Thanks for reproducer. I'll take a look later.
You can try to switch off read from backups in cache configiration:

`<property name="readFromBackup" value="false"/>`

**Comment by agura** [comment]
@onesse Did you try to reproduce problem with configuration changes suggested in the previous comment?

**Comment by onesse** [comment]
@agura , sorry for the late reply ...
No effect ! Message is always consumed twice.

**Comment by pavlafed** [comment]
I can see the same problem.  It seems updates to subs are not correctly recorded.  When node crashes, it is not removed from subs and next time it restarts, it is added one more time, hence creating duplicate registration.  This then leads to duplicate messages being sent to this node as code iterates over list of subs.

I am not sure what is causing this, maybe return null; statement on line 181 in AsyncMultiMapImpl class ?... does it prevent completing the future on line 185?

**Comment by fangtong** [comment]
The AsyncMultiMapImpl add value is not guaranteed to be unique. on line 107
![image](https://user-images.githubusercontent.com/2487726/26984479-22f046ee-4d72-11e7-96e8-f7e5c08bcaee.png)

**Comment by guoyu511** [comment]
I got the problem two. According to the interface definition in vert.x core, the key / value pair in a AsyncMultiMap should be unique.

**Comment by vietj** [comment]
perhaps there should be a test in the Vert.x clustering tests for this, WDYT @tsegismont ?

**Comment by tsegismont** [comment]
@vietj there's the io.vertx.test.core.FaultToleranceTest already in the
core test suite. It's not implemented in vertx-ignite though.

2017-06-09 23:12 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by vietj** [comment]
can we have the FaultTolerance test implemented in this project ?

**Comment by guoyu511** [comment]
@vietj I've create a PR #48 for that, including the FaultToleranceTest

**Comment by agura** [comment]
@guoyu511 Thanks for your investigation and PR. But Javadoc for `AsyncMultiMap` states:

> A multi-map holds a Set of values against each key as opposed to a single value, as with a Map. A value appears only once for a key (no duplicated values for the same key).

So I think that better way is replace List by Set.

I'll do it today and check tests.

**Comment by guoyu511** [comment]
@agura that should be the better way.

**Comment by agura** [comment]
I've committed fix https://github.com/vert-x3/vertx-ignite/pull/49
