### ISSUE TITLE
Upgrade to Ignite v2.0

### ISSUE THREAD

**Issue by ctranxuan** [vert-x3/vertx-ignite#47]
Hi,
Apache Ignite has released a new version v2.0. Some async APIs has been deprecated...
That would be great if this component could also upgrade its Ignite version.

Many thanks in advance!

Cédric.

PS : in the meantime, we will try to upgrade it manually to see whether we've got some issues or not.

**Comment by agura** [comment]
@ctranxuan I hope Ignite version will be updated in the next release of vert.x

**Comment by ctranxuan** [comment]
Having made some tests by adding the explicitly ignite 2.0, it seems to work quite well.

**Comment by agura** [comment]
@ctranxuan I've tested it with Ignite 2.0 and it seems that it works better. But I think that implementation should be changed accordingly to https://cwiki.apache.org/confluence/display/IGNITE/Apache+Ignite+2.0+Migration+Guide

In progress.
