### ISSUE TITLE
Expose underlying ignite instance

### ISSUE THREAD

**Issue by choey** [vert-x3/vertx-ignite#53]
`vertx-hazelcast` exposes the underlying hazelcast instance via `HazelcastClusterManager #getHazelcastInstance()`. One of its constructors also takes a `HazelcastInstance`, which is nice for injection and testing.

It would be nice if `vertx-ignite` expose the underlying ignite instance and allow one to be provided to a constructor.

**Comment by agura** [comment]
Thanks! I'll try to resolve this issue in 5.3.0 release.

**Comment by tipok** [comment]
Hi,

@agura you've referenced this issue from #45 We did some tests internally and came across some issues especially if running ignite in persistence mode.

Once the old data is loaded into the cluster manager vert.x is going nuts and clustering isn't working any more. We came up with following solution: 

1.  Prefixing all Vert.x internal caches
2. In the part IgniteConfiguration is already modified we added some code to disable persistence for all prefixed caches

**Comment by agura** [comment]
@tipok Did you have a chance to debug why clustering doesn't work for persistence enabled?

**Comment by tipok** [comment]
@agura the problem we've seen:

The cluster was shutdown hard and nodes had no change to leave the cluster.
After a startup a different amount of nodes was started and those have tried to communicate with nodes which weren't there. 
In fact the cluster manager does not need a possibility to persist the actual state.
If running 2.3 of ignite a different region could be created for all the ClusterManger related caches, this could configured not being persistent.
