### ISSUE TITLE
Compilation is broken due to removed ClusterWideMapTestDifferentNodes class

### ISSUE THREAD

**Issue by agura** [vert-x3/vertx-ignite#61]
Compilation is broken due to removed ClusterWideMapTestDifferentNodes class

**Comment by tsegismont** [comment]
@agura can you revert the change? I was working on a PR. Actually the class has not been removed, just renamed

**Comment by agura** [comment]
@tsegismont Thanks for pointing! I'll revert change when your PR will be done. Is it ok for you?

**Comment by tsegismont** [comment]
Actually, let me push straight with the fix, if you don't mind.

2018-01-11 16:38 GMT+01:00 Andrey Gura <notifications@github.com>:

**Comment by agura** [comment]
@tsegismont Yes, sure.
