### ISSUE TITLE
IgniteConfiguration (or IgniteInstanceName) is not exposed in IgniteClusterManager

### ISSUE THREAD

**Issue by blandger** [vert-x3/vertx-ignite#67]
Hi all
Vertx 3.5.1 with ignite-core 2.3.0

We use some custom code to start up non-web SpringBoot application and deploy Verxt instances. Ignite is deployed internally by Vertx and 'random' Ignite instance name is given on every run inside 
io.vertx.spi.cluster.ignite.IgniteClusterManager

```
public class IgniteClusterManager implements ClusterManager {
........
private IgniteConfiguration cfg;
......
  private void setNodeID(IgniteConfiguration cfg) {
    UUID uuid = UUID.fromString(nodeID);
    cfg.setNodeId(uuid);
    cfg.setIgniteInstanceName(VERTX_NODE_PREFIX + uuid); 
    // "vertx.ignite.node.e5dfa8f4-95a5-4c85-9b38-113c19f4c1c4"
  }

```
Later the cfg (or IgniteInstanceName) is not exposed at all from this manager class.

I found out following problem. I want to use started Ignite as Cache engine in SpringBoot application by utilizing:
org.apache.ignite.cache.spring.SpringCacheManager
but there is not way to initialize it correctly after Ignite is started by Vertx internally.

```
@Configuration
@ConditionalOnClass(name = "org.apache.ignite.Ignite")
@EnableCaching
public class IgniteCacheConfig {
    @Bean
    public SpringCacheManager getCacheManager() {
        SpringCacheManager springCacheManager = new SpringCacheManager();
//springCacheManager.setIgniteInstanceName("vertx.ignite.node.e5dfa8f4-95a5-4c85-9b38-113c19f4c1c4");
        return springCacheManager;
    }
```

I found one way correctly initialize SpringCacheManager by already started Ignite with help of using **exact Ignite node name**:
`springCacheManager.setIgniteInstanceName("vertx.ignite.node.e5dfa8f4-95a5-4c85-9b38-113c19f4c1c4");
`
but that is no way to extract it from Verxt internals. Other ways are not quite good. An attempt to run one Ignite node in app doesn't work.

Also I found the XML configuration property **igniteInstanceName** is ignored by Verxt code:
```
  <bean class="org.apache.ignite.configuration.IgniteConfiguration">
      <property name="igniteInstanceName" value="server-instance-0"/>
..........
```
so there is no way to 'hard-code' and use that value in SpringBoot code above.

Another suggestions are welcome.

Thanks, Yuriy.

**Comment by cinterloper** [comment]
Can you start ignite separately , then create a cluster manager,  passing ignite to it, then create Vertx? for example:
 
(groovy, the java is very similar )

       Ignite ignite = Ignition.getOrStart(cfg)
        ignite.active(true)
        ClusterManager cm = new IgniteClusterManager(ignite)

...
Vertx.clusteredVertx(new VertxOptions().setClusterManager(cm), { AsyncResult<Vertx> result ->

**Comment by tsegismont** [comment]
@cinterloper is right, instead of retrieving the instance built by Vert.x you shoud initialize an instance in Spring and provide the `IgniteClusterManager` with it.
