### ISSUE TITLE
Support Ignite async operations.

### ISSUE THREAD

**Issue by javadevmtl** [vert-x3/vertx-ignite#73]
Hi Ignite has async operation support, which allows us to do... 

```
        cache.getAsync(...)
                .listenAsync(
                        result -> {
                            System.out.println("Inner Thread:" + Thread.currentThread().getName());

                            rc.response().end("CACHED: " + result.get());},
                        VertxExecutorAdapter.getOrCreate(vertx.getOrCreateContext())); // Same as Vertx HazelCast Adapter.
 ```

Also Ignite async operations are way faster then the blocking calls from what I tested on my implementation. Unfortunately I don't have the time to take this on at the moment. But leaving it here if someone wants to tackle it.

**Comment by tsegismont** [comment]
`AsyncMap` implementation has used Ignite aync methods since #50 is merged.
