### ISSUE TITLE
ClusterWideMap ttl not working ?

### ISSUE THREAD

**Issue by jinho-xthplanet** [vert-x3/vertx-ignite#74]
Hi
I am trying to use igite cluster wide map as cache of database. And to prevent being out of memory, I need use of ttl parameter of map.put(). (version 3.6.2)

But, when I use put method with ttl, it is not expired.

Is this known issue? or Am i doing something wrong?

Jinho.

**Comment by jinho-xthplanet** [comment]
Is vertx ignite dead project? No responses are there of issues.

**Comment by vietj** [comment]
@agura ping

**Comment by tsegismont** [comment]
@jinho-xthplanet there are tests for `AsyncMap` with ttl that run fine on CI. Reopen if you still have issues. In this case, please provide a small reproducer.
