### ISSUE TITLE
AsyncMultiMapImpl implementation causes memory exhaustion

### ISSUE THREAD

**Issue by PtD** [vert-x3/vertx-ignite#75]
Hi, 
When there are high number of messages published on the event bus (in the range of several thousands per second), the **AsyncMultiMapImpl#get** implementation is adding elements to taskQueue faster that they are drained - all tasks are executed sequentially in a single thread. Eventually, it causes all the heap memory to be consumed.

Other cluster managers don't use blocking calls for **AsyncMultiMapImpl#get** and are able to support much higher event bus throughput.

The problem persists from vert.x 3.4 to the current 3.7.x.

**Comment by tsegismont** [comment]
Resolved in #82
