### ISSUE TITLE
Handlers with same address do not receive messages on a round-robin basis when in separate Vert.x Ignite cluster nodes

### ISSUE THREAD

**Issue by patrickvankann** [vert-x3/vertx-ignite#8]
When two instances of the same handler are registered on the same address but in different Vert.x cluster instances and the IgniteClusterManager is used, they do not alternate in receiving messages from a sender. When they are on the same cluster node, this behaviour works.

The HazelcastClusterManager works as expected in both scenarios.

There is a reproducer project being created in GitHub. See updates.

**Comment by patrickvankann** [comment]
https://github.com/patrickvankann/vertx-ignite-issue-8-reproducer 

Import to Eclipse as Maven project and then choose Reproducer.java and "Run As --> Java program".

This will start a 3 node Vertx Ignite cluster. The console output will show that always the same Receiver instance receives the message from Sender instead of alternating.

**Comment by patrickvankann** [comment]
I checked out your pull request, rebuilt 3.3.0 and can verify this seems to address the issue. Cheers!

**Comment by agura** [comment]
Thanks for feedback. Merged into master.
