### ISSUE TITLE
refactor ignite configuration

### ISSUE THREAD

**Issue by zyclonite** [vert-x3/vertx-ignite#85]
#### Describe the feature

Switch to a programmatic vertx default config and migrate xml based configuration overrides to json configs. Removes ignite-spring dependency.

#### Use cases

Remove a lot of overhead which is only used for config parsing.

#### Contribution

@tsegismont what so you think of this approach? https://github.com/zyclonite/vertx-ignite/commit/053d96df0f745f2ef2673dcc6823553256a0c32b

**Comment by tsegismont** [comment]
I add a quick look at the branch. IIUC the spring dependency was only needed to use a Spring XML config?

**Comment by zyclonite** [comment]
yes, my approach now would be to start with modeling only discovery and cache options as this will be the only overrides used by most of the users

if they need more, they can still inject the initialized ignite or inject the config into the cluster manager

**Comment by zyclonite** [comment]
@tsegismont would you continue going that path or leave it as is?

**Comment by tsegismont** [comment]
@agura what do you think about this proposal?

**Comment by zyclonite** [comment]
@agura any news on that?

**Comment by zyclonite** [comment]
@tsegismont i fear we will not get an answer...

as this will be a breaking change, would be a good chance to get it ready before the 4.x release, if it's not already too late

**Comment by tsegismont** [comment]
@zyclonite send a PR, I'll review it.

**Comment by zyclonite** [comment]
@tsegismont that's the PR https://github.com/vert-x3/vertx-ignite/pull/88
could not resist to do some cleanups for logging as well...
