### ISSUE TITLE
Ignite cache operation block indefinitely until cluster establishes it's state.

### ISSUE THREAD

**Issue by javadevmtl** [vert-x3/vertx-ignite#89]
### Version

3.9.x plus latest releases
Ignite 2.7.0

### Context

Looking at the code when you apply the cache operation even if IgniteFuture is supposed to be async. The ignite operation will block until the cluster is in good state.

### Do you have a reproducer?

No you need an Ignite cluster

### Steps to reproduce

1- Spin up ignite cluster
2- Make sure you have basic topology take down a node or two and run operations.
3- Restart cluster while cluster is rebalancing do more operations.

The caheoperation.apply() in executeAsync() seems to block.

**Comment by javadevmtl** [comment]
I did something like this for my ignite implementation...

```
    private <T> Future<T> executeAsync(Function<IgniteCache<K, V>, IgniteFuture<T>> cacheOperation, long timeoutMs) {
        final Promise<T> promise = Promise.promise();

        vertx.setTimer(timeoutMs, id -> {
            promise.tryFail(new TimeoutException("Cache operation did not complete within: " + timeoutMs + " Ms."));
        });

        vertx.<T>executeBlocking(code -> {
            try {
                IgniteFuture<T> value = cacheOperation.apply(cache); // <----- This can actually block!!!!

                value.listenAsync(result -> {
                    try {
                        code.complete(result.get());
                    } catch(Exception ex) {
                        code.fail(ex);
                    }
                }, VertxIgniteExecutorAdapter.getOrCreate(vertx.getOrCreateContext()));
            } catch(Exception ex) {
                // Catch some RuntimeException that can be thrown by Ignite cache.
                code.fail(ex);
            }
        }, result -> {
                if(result.succeeded())
                    promise.complete(result.result());
                else
                    promise.tryFail(result.cause());
        });

        return promise.future();
    }
```

**Comment by tsegismont** [comment]
@javadevmtl can you check with Ignite folks why this operation may block? Thank you

**Comment by javadevmtl** [comment]
Hi I have a thread going here, waiting for answers.

https://mail.google.com/mail/u/1/#label/Apache+Ignite/KtbxLwgwzkkWFwFgjfcKtCfbrjKmfwLpLq

**Comment by javadevmtl** [comment]
And here is an official bug recorded: https://issues.apache.org/jira/browse/IGNITE-13372

The gist of it is that if the ignite cluster is setup to use persistence which requires the cluster to be in active state then the IgniteCache instance starts to block. A dirty workaround is to listen for events and somehow re-init a new IgniteCache instance.

I guess for now maybe it should be a documented issue.

**Comment by tsegismont** [comment]
We have this issue reported thanks to you. I believe it is enough as we cannot document each corner case in the reference manual.

**Comment by zyclonite** [comment]
since version 4.0.3 there is a `shutdownOnNodeStop` flag in the `IgniteOptions` which would shutdown vertx if the ignite node gets inactive

**Comment by zyclonite** [comment]
closing the issue due to inactivity, if this is still an issue we can reopen it
