### ISSUE TITLE
Instantiate IgniteClusterManager with Ignite Spring configuration xml file URL

### ISSUE THREAD

**Issue by alexGalushka** [vert-x3/vertx-ignite#9]
It's useful for testing purposes especially with PowerMockito, it's related to the issue when class loader is mocked along with static classes, it sort of described [here](http://stackoverflow.com/questions/16520699/mockito-powermock-linkageerror-while-mocking-system-class).

[Here ](https://gist.github.com/alexGalushka/8bdc30acfbc6b54169b8)is the gist for it.

**Comment by alexGalushka** [comment]
@agura Let me know if you would like be to submit a PR for this...

**Comment by agura** [comment]
@alexGalushka Could you please create corresponding PR? I'll review and merge it. Thx.

**Comment by alexGalushka** [comment]
@agura Done, https://github.com/vert-x3/vertx-ignite/pull/11

**Comment by agura** [comment]
Revied and merged.

Thanks.
